name: happy_holidays
description: Just a project to have fun


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  functional_data:
  http:
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  functional_data_generator:
  json_serializable:
  mockito:


flutter:
  uses-material-design: true
